<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lobby</title>

    <link href="../css/styles.css" rel="stylesheet" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<body>
    <div class="verticalCentered">
        <h1>Welcome To Battleship</h1>

        <form>
            <input type="text" placeholder="nickname" autocomplete="off" name="nickname" id="nickname" />
            <button type="submit">&gt;&gt; Find an opponent &lt;&lt;</button>
        </form>
    </div>

</body>
</html>