<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Waiting Lodge</title>

    <link href="../css/styles.css" rel="stylesheet" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<body>
    <div class="verticalCentered">
        <h3>Please be patient. We are searching for an opponent...</h3>
    </div>
   

    <script src="../js/lodge.js"></script>
</body>
</html>
